# --- values.yaml ---
extraScrapeConfigs: |
  # - job_name: echo-server
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets: ["echo-server.production.svc.cluster.local:80"]
  #       labels:
  #         namespace: production
  #         app: echo-server

  - job_name: gateway-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["gateway-service.production.svc.cluster.local:80"]
        labels:
          namespace: production
          app: gateway-service

  - job_name: media-catalog-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["media-catalog-service.production.svc.cluster.local:80"]
        labels:
          namespace: production
          app: media-catalog-service

  - job_name: playback-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["playback-service.production.svc.cluster.local:80"]
        labels:
          namespace: production
          app: playback-service

  - job_name: youtube-fetcher-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["youtube-fetcher-service.production.svc.cluster.local:80"]
        labels:
          namespace: production
          app: youtube-fetcher-service

  - job_name: web-client
    metrics_path: /metrics
    static_configs:
      - targets: ["web-client.production.svc.cluster.local:80"]
        labels:
          namespace: production
          app: web-client

  # # ----- 인프라/데이터베이스 -------------------------------------------
  # # Postgres – exporter 노출 포트가 9187 (변경 필요 시 수정)
  # - job_name: postgres
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets: ["loopin-postgres.production.svc.cluster.local:9187"]
  #       labels:
  #         namespace: production
  #         app: postgres

  # # Redis – exporter 노출 포트가 9121 (변경 필요 시 수정)
  # - job_name: redis
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets:
  #         - "loopin-redis.production.svc.cluster.local:9121"
  #         - "loopin-media-catalog-redis.production.svc.cluster.local:9121"
  #       labels:
  #         namespace: production
  #         app: redis

# 필요하다면 전역 scrape 간격/타임아웃도 함께 조정
# scrapeInterval: 30s
# evaluationInterval: 30s
