apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-accel-config
  namespace: loopin-production
data:
  nginx.conf: |
    worker_processes auto;

    events {
      worker_connections 4096;
    }

    http {
      include /etc/nginx/mime.types;
      default_type application/octet-stream;
      
      # 로깅
      log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
      
      access_log /var/log/nginx/access.log main;
      error_log /var/log/nginx/error.log warn;
      
      # 성능 최적화
      sendfile on;
      tcp_nopush on;
      tcp_nodelay on;
      keepalive_timeout 65;
      
      # 파일 캐시
      open_file_cache max=10000 inactive=20s;
      open_file_cache_valid 30s;
      open_file_cache_min_uses 2;
      open_file_cache_errors on;
      
      server {
        listen 80;
        server_name _;
        
        # 관리 서버로 proxy (권한 검증)
        location /api/v1/streams {
          proxy_pass http://streaming-service;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          
          # 타임아웃
          proxy_connect_timeout 10s;
          proxy_send_timeout 30s;
          proxy_read_timeout 30s;
        }
        
        # 내부 전용: HLS 파일 서빙
        location /_internal/hls/ {
          internal;
          alias /hlsroot/;
          
          # CORS 헤더
          add_header Access-Control-Allow-Origin "*" always;
          add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS" always;
          add_header Access-Control-Allow-Headers "Range" always;
          
          # 캐시 헤더 - 실시간 스트림은 no-cache
          add_header Cache-Control "no-cache, no-store, max-age=0, must-revalidate";
          
          # MIME 타입
          types {
            application/vnd.apple.mpegurl m3u8;
            video/mp2t ts;
            application/octet-stream m4s;
          }
          
          # Range request 지원
          add_header Accept-Ranges bytes;
        }
        
        # Health check
        location /health {
          access_log off;
          return 200 "healthy\n";
          add_header Content-Type text/plain;
        }
      }
    }
