apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loopin-production

resources:
  - ../../../base/nginx-accel

patches:
  - path: deployment-patch.yaml
  - path: configmap-patch.yaml
