apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-fetcher-service
  labels:
    app: youtube-fetcher-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtube-fetcher-service
  template:
    metadata:
      labels:
        app: youtube-fetcher-service
    spec:
      serviceAccountName: youtube-fetcher-sa
      containers:
        - name: youtube-fetcher-service
          image: ghcr.io/sglee487/loopin-server/youtube-fetcher-service:4e78faaf9722d7404e572e629db10e26607b72f7
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: youtube-api-key-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          volumeMounts:
            - name: youtube-fetcher-config-volume
              mountPath: /workspace/config
      volumes:
        - name: youtube-fetcher-config-volume
          configMap:
            name: youtube-fetcher-service-config
