apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming-service
  template:
    spec:
      containers:
        - name: streaming-service
          image: ghcr.io/sglee487/loopin-server/streaming-service:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: R2DBC_USERNAME
              value: "postgres"
            - name: R2DBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: streaming-service-postgresql
                  key: postgres-password
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: BPL_JVM_DIRECT_MEMORY
              value: "128M"
            - name: BPL_JVM_HEAP_RATIO
              value: "0.6"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-2.18.1.jar"
            - name: OTEL_SERVICE_NAME
              value: "streaming-service"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://tempo.monitoring.svc.cluster.local:4317"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_LOGS_EXPORTER
              value: "none"
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "768Mi"
              cpu: "1000m"
