apiVersion: v1
kind: Service
metadata:
  name: loki-svc
  namespace: monitoring
  labels:
    app: loki
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3100
      targetPort: 3100
  selector:
    app: loki
