apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loopin-production

resources:
  - ../../../base/youtube-fetcher-service
  - youtube-api-key-secret.yaml

configMapGenerator:
  - name: youtube-fetcher-service-config
    behavior: merge
    files:
      - application-prod.yml

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: youtube-fetcher-service
