apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-accel-config
  namespace: loopin-production
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      server {
        listen 80;
        
        location /api/v1/streams {
          proxy_pass http://streaming-service;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }
        
        location /_internal/hls/ {
          internal;
          alias /hlsroot/;
          
          types {
            application/vnd.apple.mpegurl m3u8;
            video/mp2t ts;
          }
        }
      }
    }
