apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loopin-production

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - nginx-sa.yaml
  - nginx-rbac.yaml
