apiVersion: v1
kind: ConfigMap
metadata:
    name: nginx-config
    namespace: loopin-production
data:
    nginx.conf: |
        events {
            worker_connections 1024;
        }

        http {
            include       /etc/nginx/mime.types;
            default_type  application/octet-stream;

            server {
                listen 80;
                server_name _;

                # 스트리밍 서비스로 프록시 (권한 체크 + X-Accel-Redirect 응답)
                location /api/v1/streams {
                    proxy_pass http://streaming-service:8080;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                }

                # 내부 전용: 실제 HLS 파일을 직접 전송
                location /_internal/hls/ {
                    internal;              # 클라이언트 직접 접근 차단
                    alias /usr/share/nginx/html/live/;
                    sendfile on;
                    tcp_nopush on;

                    # CORS 헤더
                    add_header Access-Control-Allow-Origin "*";

                    # MIME 타입 설정
                    location ~* \.m3u8$ {
                        add_header Content-Type application/vnd.apple.mpegurl;
                        add_header Access-Control-Allow-Origin "*";
                    }

                    location ~* \.ts$ {
                        add_header Content-Type video/mp2t;
                        add_header Access-Control-Allow-Origin "*";
                    }

                    location ~* \.m4s$ {
                        add_header Content-Type application/octet-stream;
                        add_header Access-Control-Allow-Origin "*";
                    }
                }

                # SRS HTTP API 프록시
                location /api/srs/ {
                    proxy_pass http://localhost:1985/;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                }

                # SRS HTTP 서버 프록시
                location /srs/ {
                    proxy_pass http://localhost:8080/;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                }
            }
        }
