apiVersion: apps/v1
kind: Deployment
metadata:
  name: srs-nginx-deploy
  namespace: loopin-production
  labels:
    app: srs-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srs-nginx
  template:
    metadata:
      labels:
        app: srs-nginx
    spec:
      volumes:
        - name: hls-storage
          persistentVolumeClaim:
            claimName: hls-storage-pvc
        - name: nginx-config
          configMap:
            name: nginx-config
      containers:
        - name: srs
          image: ossrs/srs:6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1935
            - containerPort: 1985
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: hls-storage
              mountPath: /usr/local/srs/objs/nginx/html
              readOnly: false
        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          volumeMounts:
            - name: hls-storage
              mountPath: /usr/share/nginx/html
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf

---
apiVersion: v1
kind: Service
metadata:
  name: srs-nginx-service
  namespace: loopin-production
spec:
  type: ClusterIP
  selector:
    app: srs-nginx
  ports:
    - name: nginx-http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: srs-rtmp
      port: 1935
      protocol: TCP
      targetPort: 1935
    - name: srs-api
      port: 1985
      protocol: TCP
      targetPort: 1985
    - name: srs-http
      port: 8080
      protocol: TCP
      targetPort: 8080
