apiVersion: apps/v1
kind: Deployment
metadata:
  name: playback-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: playback-service
  template:
    spec:
      containers:
      - name: playback-service
        image: ghcr.io/sglee487/loopin-server/playback-service:latest
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: R2DBC_USERNAME
          value: "postgres"
        - name: R2DBC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: playback-service-postgresql
              key: postgres-password
        resources:
          requests:
            memory: "256Mi"
            cpu: "125m"
          limits:
            memory: "512Mi"
            cpu: "250m"