apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert
  namespace: default
spec:
  secretName: tls-secret
  issuerRef:
    name: tls-issuer
  commonName: CHANGE_ME
  dnsNames:
    - CHANGE_ME
    - CHANGE_ME
    - CHANGE_ME
    - CHANGE_ME 