apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: tls-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: CHANGE_ME
    privateKeySecretRef:
      name: tls-key
    solvers:
      - selector: {}
        http01:
          ingress:
            class: traefik 