apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-service
  template:
    spec:
      containers:
        - name: gateway-service
          image: ghcr.io/sglee487/loopin-server/gateway-service:9d34854f48600111e7d045871d7d4b2f84840275
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: gateway-keycloak-client-secret
                  key: client-secret
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: gateway-config-volume
          configMap:
            name: gateway-service-config
