apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loopin-production

resources:
  - ../../../base/gateway-service
  - gateway-keycloak-client-secret.yaml

images:
  - name: ghcr.io/sglee487/loopin-server/gateway-service
    newTag: 9d34854f48600111e7d045871d7d4b2f84840275

configMapGenerator:
  - name: gateway-service-config
    behavior: merge
    files:
      - application-prod.yml

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: gateway-service
