architecture: standalone

image:
  registry: docker.io
  repository: bitnamilegacy/redis
  tag: 8.2.1-debian-12-r0

master:
  persistence:
    size: 2Gi
  resources:
    limits:
      memory: 512Mi
      cpu: 300m
    requests:
      memory: 128Mi
      cpu: 100m

global:
  security:
    allowInsecureImages: true
