apiVersion: v1
kind: ConfigMap
metadata:
  name: srs-config
  namespace: loopin-production
data:
  srs.conf: |
    listen 1935;
    max_connections 1000;
    daemon off;

    http_api {
        enabled on;
        listen 1985;
    }

    http_server {
        enabled on;
        listen 8080;
        dir /usr/local/srs/objs/nginx/html;
    }

    vhost __defaultVhost__ {
        hls {
            enabled on;
            hls_path /usr/local/srs/objs/nginx/html;
            hls_fragment 4;
            hls_window 20;
            hls_m3u8_file [app]/[stream]/index.m3u8;
            hls_ts_file [app]/[stream]/[seq].ts;
        }
        
        http_hooks {
            enabled on;
            on_publish http://streaming-service/api/v1/hooks/on_publish;
            on_unpublish http://streaming-service/api/v1/hooks/on_unpublish;
        }
    }
