apiVersion: v1
kind: Service
metadata:
  name: srs-service
  namespace: loopin-production
spec:
  type: ClusterIP
  selector:
    app: srs-server
  ports:
    - name: srs-service-1935-1935
      port: 1935
      protocol: TCP
      targetPort: 1935
    - name: srs-service-1985-1985
      port: 1985
      protocol: TCP
      targetPort: 1985
    - name: srs-service-8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
