apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  labels:
    app: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: ghcr.io/sglee487/loopin-server/gateway-service:a458999ab363d34fc64ecb961c2ce6f60f286ed0
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          envFrom:
            - configMapRef:
                name: gateway-service-config
          volumeMounts:
            - name: gateway-config-volume
              mountPath: /workspace/config
      volumes:
        - name: gateway-config-volume
          configMap:
            name: gateway-service-config
      serviceAccountName: gateway-sa
