apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-catalog-service
  labels:
    app: media-catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-catalog-service
  template:
    metadata:
      labels:
        app: media-catalog-service
    spec:
      serviceAccountName: media-catalog-sa
      containers:
        - name: media-catalog-service
          image: ghcr.io/sglee487/loopin-server/media-catalog-service
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
          volumeMounts:
            - name: media-catalog-config-volume
              mountPath: /workspace/config
      volumes:
        - name: media-catalog-config-volume
          configMap:
            name: media-catalog-service-config
