persistence:
  type: pvc
  enabled: true

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        url: http://loki-svc.monitoring.svc.cluster.local:3100
        access: proxy
        isDefault: true
      - name: Tempo
        type: tempo
        url: http://tempo.monitoring.svc.cluster.local:3200
        access: proxy
        isDefault: false
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local:80
        access: proxy
        isDefault: false

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  labels: {}
  path: /
  pathType: Prefix
  hosts:
    - grafana.loopin.bid
  extraPaths: []
  tls:
    - secretName: wildcard-tls
      hosts:
        - grafana.loopin.bid
