apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loopin-production

namePrefix: prod-

resources:
  - ../../base
  - ingress.yaml
  - media-catalog-service/cronjob-youtube-sync.yaml
  - youtube-fetcher-service/youtube-api-key-secret.yaml

images:
  - name: ghcr.io/sglee487/loopin-server/media-catalog-service
    newTag: 9055db816599fb2f6bbc6e9ce77a408920e99204 # CI will replace this tag with the commit SHA or desired version

patches:
  - path: gateway-service/deployment-patch.yaml
    target:
      kind: Deployment
      name: gateway-service
  - path: media-catalog-service/deployment-patch.yaml
    target:
      kind: Deployment
      name: media-catalog-service
  - path: playback-service/deployment-patch.yaml
    target:
      kind: Deployment
      name: playback-service
  - path: youtube-fetcher-service/deployment-patch.yaml
    target:
      kind: Deployment
      name: youtube-fetcher-service
