replicaCount: 1

image:
  registry: docker.io
  repository: bitnamilegacy/keycloak
  tag: 26.3.3-debian-12-r0

postgresql:
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: 17.6.0-debian-12-r0

tls:
  enabled: false

ingress:
  enabled: true
  ingressClassName: traefik
  hostname: auth.loopin.bid
  annotations:
    traefik.ingress.kubernetes.io/ingress.class: traefik
  tls: true
  servicePort: http

auth:
  adminUser: admin

production: true
proxy: edge
proxyHeaders: xforwarded # ← 추가

resources:
  requests:
    memory: 1Gi
    cpu: 1000m
  limits:
    memory: 2Gi
    cpu: 2000m
