apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-client
  namespace: loopin-production
  labels:
    app: web-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-client
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/metrics"
      labels:
        app: web-client
    spec:
      serviceAccountName: web-client-sa
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: web-client
          image: ghcr.io/sglee487/loopin-client:675f1b761d32f0c968fc2c0d1392e4fecfe0632b
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_BASE_URL
              value: "https://api.loopin.bid"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
      volumes:
        - name: web-client-config-volume
          configMap:
            name: web-client-config
