apiVersion: apps/v1
kind: Deployment
metadata:
  name: playback-service
  labels:
    app: playback-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playback-service
  template:
    metadata:
      labels:
        app: playback-service
    spec:
      serviceAccountName: playback-sa
      containers:
        - name: playback-service
          image: ghcr.io/sglee487/loopin-server/playback-service:ead79043bdac454512f52a3e2e46d948c030f468
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
          volumeMounts:
            - name: playback-config-volume
              mountPath: /workspace/config
      volumes:
        - name: playback-config-volume
          configMap:
            name: playback-service-config
