apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-service
  labels:
    app: streaming-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming-service
  template:
    metadata:
      labels:
        app: streaming-service
    spec:
      serviceAccountName: streaming-sa
      containers:
        - name: streaming-service
          image: ghcr.io/sglee487/loopin-server/streaming-service:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
          volumeMounts:
            - name: streaming-config-volume
              mountPath: /workspace/config
      volumes:
        - name: streaming-config-volume
          configMap:
            name: streaming-service-config
