apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hls-storage-pvc
  namespace: loopin-production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  # storageClassName은 overlay에서 패치
